name = "my-astro-app"
main = "./dist/_worker.js/index.js"
compatibility_date = "2024-04-14"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

[build]
command = "npm run build"
watch_dir = "src"

[env.production]
zone_id = "c9bd4a0591d9dce7af89a93358dc0eb1"
account_id = "2cc579c1ec9e426ed585e933ebf4753b"
route = "homesatlonemountain.com/*"
workers_dev = false

# Security Headers
[env.production.headers]
"/*" = [
  { key = "Content-Security-Policy", value = "default-src 'self' https://*.realscout.com https://*.cloudflare.com; script-src 'self' 'unsafe-inline' https://*.realscout.com https://*.cloudflare.com; style-src 'self' 'unsafe-inline' https://*.realscout.com; img-src 'self' data: https://*.realscout.com https://*.cloudflare.com https://*.imagedelivery.net; connect-src 'self' https://*.realscout.com https://*.cloudflare.com;" },
  { key = "X-Content-Type-Options", value = "nosniff" },
  { key = "X-Frame-Options", value = "DENY" },
  { key = "X-XSS-Protection", value = "1; mode=block" },
  { key = "Referrer-Policy", value = "strict-origin-when-cross-origin" },
  { key = "Permissions-Policy", value = "camera=(), microphone=(), geolocation=(self), interest-cohort=()" }
]

[env.production.analytics]
token = "${CLOUDFLARE_ANALYTICS_TOKEN}"
beacon = true
scriptPath = "/analytics.js"
spa = true

[env.staging]
workers_dev = true

# Cache Configuration
[env.production.cache_settings]
browser_ttl = 3600
edge_ttl = 86400
cache_by_device_type = true
cache_deception_armor = true
always_online = true
cache_reserve = true

[[kv_namespaces]]
binding = "SITE_CACHE"
id = "cache"
preview_id = "cache_preview"

[triggers]
crons = ["0 0 * * *"] # Daily at midnight

[miniflare]
kv_persist = true
cache_persist = true

# Asset Optimization
[env.production.assets]
compress = true
minify = true
http3 = true
0rtt = true
brotli = true
http2_push_assets = true
polish = "lossy"
webp = true
quality = 85

# Security Rules
[env.production.security]
waf = true
bot_management = true
ddos_l7 = true
ssl = "strict"
always_use_https = true
opportunistic_encryption = true
automatic_https_rewrites = true
ip_geolocation = true
browser_check = true
challenge_ttl = 31536000
privacy_pass = true

[[r2_buckets]]
binding = "SITE_ASSETS"
bucket_name = "site-assets"
preview_bucket_name = "site-assets-preview"

# Rate Limiting Rules
[[rules]]
type = "rate_limit"
expression = '(http.request.uri.path matches "^/api/.*$")'
period = 60
requests_per_period = 100
mitigation_timeout = 600
globs = ["api/*"]

# Web Analytics
[web_analytics]
site_tag = "homes-at-lone-mountain"
token = "${CLOUDFLARE_ANALYTICS_TOKEN}"
spa = true

# Image Optimization
[images]
default_quality = 85
preserve_exif = false
metadata_honor = false
formats = ["avif", "webp"]
sizes = [400, 800, 1200, 1920]

[assets]
binding = "ASSETS"
bucket = "./dist"
include = ["**/*"]

[observability]
enabled = true 